In [50]:
# Importation des librairies

import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
import sklearn
from sklearn import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

In [51]:
# Charger les données Iris
data = datasets.load_iris()

# Créer un DataFrame pandas à partir des données
df = pd.DataFrame(data.data, columns=data.feature_names)

# Sélectionner uniquement certaines colonnes
colonnes_specifiques = ['petal length (cm)', 'petal width (cm)']
df_subset = df[colonnes_specifiques]

# Afficher les premières lignes du DataFrame subset
print(df_subset.head(10))

   petal length (cm)  petal width (cm)
0                1.4               0.2
1                1.4               0.2
2                1.3               0.2
3                1.5               0.2
4                1.4               0.2
5                1.7               0.4
6                1.4               0.3
7                1.5               0.2
8                1.4               0.2
9                1.5               0.1


In [52]:
# Ajouter la colonne de la cible (target) à DataFrame
df['target'] = data.target

# Séparer les caractéristiques (features) et les cibles (targets)
X = df.drop(['target', 'sepal length (cm)', 'sepal width (cm)'], axis=1)
y = df['target']


In [53]:
# Les noms des targets

data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [54]:
# Combien y a-t-il d'exemples de chaque classe ?

np.bincount(data.target)

array([50, 50, 50], dtype=int64)

In [77]:
# Création jeu d'apprentissage et de test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [78]:
# Construire un arbre de décision

classifier_tree = DecisionTreeClassifier()

In [79]:
# Construire un arbre de décision

classifier_tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [80]:
predictions = classifier_tree.predict(X_test)
print(predictions) # modèle qui a prédit 

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 1 0 0 1 1 0]


In [81]:
# Calculer le taux de performance du modèle

accuracy = classifier_tree.score(X_test, y_test)
print("Le teux de performance est de :", accuracy)

Le teux de performance est de : 0.9666666666666667


In [82]:
print(confusion_matrix(y_test,predictions))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [83]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



In [85]:
# Faire une fonction qui test le paramètre max_depth du 3 au 10

for mdepth in [3,4,5,6,7,8,9,10]:
    clf = tree.DecisionTreeClassifier(max_depth=mdepth)
    clf = clf.fit(X_train, y_train)
    print("L'accuracy avec le paramètre max_depth=", mdepth, " est de : ",(clf.score(X_test, y_test)))

L'accuracy avec le paramètre max_depth= 3  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 4  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 5  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 6  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 7  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 8  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 9  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 10  est de :  0.9666666666666667


In [86]:
# Faire une fonction qui test le paramètre max_depth du 3 au 10

for mdepth in [3,4,5,6,7,8,9,10]:
    clf = tree.DecisionTreeClassifier(max_depth=mdepth)
    clf = clf.fit(X_train, y_train)
    print("L'accuracy avec le paramètre max_depth=", mdepth, " est de : ",(clf.score(X_train, y_train)))

L'accuracy avec le paramètre max_depth= 3  est de :  0.9666666666666667
L'accuracy avec le paramètre max_depth= 4  est de :  0.9833333333333333
L'accuracy avec le paramètre max_depth= 5  est de :  0.9916666666666667
L'accuracy avec le paramètre max_depth= 6  est de :  0.9916666666666667
L'accuracy avec le paramètre max_depth= 7  est de :  0.9916666666666667
L'accuracy avec le paramètre max_depth= 8  est de :  0.9916666666666667
L'accuracy avec le paramètre max_depth= 9  est de :  0.9916666666666667
L'accuracy avec le paramètre max_depth= 10  est de :  0.9916666666666667


In [87]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,
    test_size=0.30, random_state=0)
from sklearn.model_selection import GridSearchCV
pgrid = {"max_depth": [1, 2, 3, 4, 5, 6, 7],
      "min_samples_split": [2, 3, 5, 10, 15, 20]}
grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid=pgrid, cv=10)
grid_search.fit(X_train, y_train)
grid_search.best_estimator_.score(X_test, y_test)


0.9777777777777777